spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  profiles:
    active: local
  application:
    name: IryeokFitAi
  datasource:
    url: jdbc:mysql://iryeokfit-mysql:3306/iryeokfit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: iryeokfit
    password: IryeokFit
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
